name: videosdk_hls_demo
description: VideoSDK HLS Demo.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chewie: ^1.3.3
  cupertino_icons: ^1.0.2
  date_time_format: ^2.0.1
  dio: ^4.0.6
  video_player: ^2.4.2
  videosdk: ^0.0.12

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
